<?php 

if ( function_exists( 'lazyblocks' ) ) :

    lazyblocks()->add_block( array(
        'id' => 21027,
        'title' => 'Table of content',
        'icon' => '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M21 3H3c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h18c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zm-9 8H3V9h9v2zm0-4H3V5h9v2z" /></svg>',
        'keywords' => array(
            0 => 'содержание',
            1 => 'toc',
            2 => 'tableofcontent',
        ),
        'slug' => 'lazyblock/toc',
        'description' => 'Table of content',
        'category' => 'lazyblocks',
        'category_label' => 'lazyblocks',
        'supports' => array(
            'customClassName' => true,
            'anchor' => false,
            'align' => array(
                0 => 'wide',
                1 => 'full',
            ),
            'html' => false,
            'multiple' => false,
            'inserter' => true,
        ),
        'ghostkit' => array(
            'supports' => array(
                'spacings' => false,
                'display' => false,
                'scrollReveal' => false,
                'frame' => false,
                'customCSS' => false,
            ),
        ),
        'controls' => array(
            'control_ec182d4ca9' => array(
                'type' => 'number',
                'name' => 'top',
                'default' => '2',
                'label' => 'top',
                'help' => '',
                'child_of' => '',
                'placement' => 'inspector',
                'width' => '100',
                'hide_if_not_selected' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'required' => 'false',
                'min' => '1',
                'max' => '7',
                'step' => '',
                'placeholder' => '',
                'characters_limit' => '',
            ),
            'control_24bb2d43b9' => array(
                'type' => 'number',
                'name' => 'bottom',
                'default' => '2',
                'label' => 'bottom',
                'help' => '',
                'child_of' => '',
                'placement' => 'inspector',
                'width' => '100',
                'hide_if_not_selected' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'required' => 'false',
                'min' => '2',
                'max' => '7',
                'step' => '',
                'placeholder' => '',
                'characters_limit' => '',
            ),
            'control_37a9fd4662' => array(
                'type' => 'text',
                'name' => 'type',
                'default' => 'u',
                'label' => 'type',
                'help' => '',
                'child_of' => '',
                'placement' => 'inspector',
                'width' => '100',
                'hide_if_not_selected' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'required' => 'false',
                'placeholder' => 'u or o',
                'characters_limit' => '1',
            ),
            'control_7018354959' => array(
                'type' => 'text',
                'name' => 'content',
                'default' => 'article',
                'label' => 'content',
                'help' => 'set selector for content container',
                'child_of' => '',
                'placement' => 'inspector',
                'width' => '100',
                'hide_if_not_selected' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'required' => 'false',
                'placeholder' => 'selector',
                'characters_limit' => '',
            ),
            'control_252a5a4a9a' => array(
                'type' => 'text',
                'name' => 'header',
                'default' => 'Содержание',
                'label' => 'header',
                'help' => '',
                'child_of' => '',
                'placement' => 'content',
                'width' => '100',
                'hide_if_not_selected' => 'false',
                'save_in_meta' => 'false',
                'save_in_meta_name' => '',
                'required' => 'false',
                'placeholder' => '',
                'characters_limit' => '',
            ),
        ),
        'code' => array(
            'output_method' => 'template',
            'editor_html' => '',
            'editor_callback' => '',
            'editor_css' => '',
            'frontend_html' => '',
            'frontend_callback' => '',
            'frontend_css' => '',
            'show_preview' => 'never',
            'single_output' => false,
        ),
        'condition' => array(
        ),
    ) );
    
endif;